2025-03-05 10:55:05,808 INFO    MainThread:469 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-05 10:55:05,809 INFO    MainThread:469 [wandb_setup.py:_flush():67] Configure stats pid to 469
2025-03-05 10:55:05,809 INFO    MainThread:469 [wandb_setup.py:_flush():67] Loading settings from /root/.config/wandb/settings
2025-03-05 10:55:05,809 INFO    MainThread:469 [wandb_setup.py:_flush():67] Loading settings from /home/duckietown_rl_course/duckiesim/rl/wandb/settings
2025-03-05 10:55:05,809 INFO    MainThread:469 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-05 10:55:05,809 INFO    MainThread:469 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/duckietown_rl_course/duckiesim/rl/wandb/run-20250305_105505-493rc17z/logs/debug.log
2025-03-05 10:55:05,809 INFO    MainThread:469 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/duckietown_rl_course/duckiesim/rl/wandb/run-20250305_105505-493rc17z/logs/debug-internal.log
2025-03-05 10:55:05,810 INFO    MainThread:469 [wandb_init.py:init():761] calling init triggers
2025-03-05 10:55:05,810 INFO    MainThread:469 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'exp_name': 'munchausen', 'seed': 1, 'torch_deterministic': True, 'cuda': True, 'track': True, 'wandb_project_name': 'DuckieTownRL', 'wandb_entity': None, 'capture_video': False, 'save_model': True, 'upload_model': False, 'hf_entity': '', 'env_id': 'DuckietownDiscrete-v0', 'total_timesteps': 10000000, 'learning_rate': 0.0002, 'num_envs': 1, 'buffer_size': 1000000, 'gamma': 0.99, 'tau': 1.0, 'target_network_frequency': 4, 'batch_size': 128, 'start_e': 1, 'end_e': 0.01, 'exploration_fraction': 0.1, 'learning_starts': 10000, 'train_frequency': 8, 'tau_soft': 0.03, 'alpha': 0.9, 'l_0': -1.0, 'epsilon_tar': 1e-06, 'polyak': 0.995, 'load_dataset': True, 'file_dataset': '/home/duckietown_rl_course/duckiesim/manual/dataset/expert_data_36591.parquet', 'save_dataset': False, 'file_name': 'training_data', 'plotext': True, 'per_data': 1.0, '_wandb': {'code_path': 'code/munchausen.py'}}
2025-03-05 10:55:05,810 INFO    MainThread:469 [wandb_init.py:init():784] starting backend
2025-03-05 10:55:05,810 INFO    MainThread:469 [wandb_init.py:init():788] sending inform_init request
2025-03-05 10:55:05,836 INFO    MainThread:469 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-05 10:55:05,837 INFO    MainThread:469 [wandb_init.py:init():803] backend started and connected
2025-03-05 10:55:05,840 INFO    MainThread:469 [wandb_init.py:init():896] updated telemetry
2025-03-05 10:55:05,858 INFO    MainThread:469 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-05 10:55:06,204 INFO    MainThread:469 [wandb_init.py:init():995] starting run threads in backend
2025-03-05 10:55:06,334 INFO    MainThread:469 [wandb_run.py:_console_start():2377] atexit reg
2025-03-05 10:55:06,334 INFO    MainThread:469 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-05 10:55:06,334 INFO    MainThread:469 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-05 10:55:06,335 INFO    MainThread:469 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-05 10:55:06,336 INFO    MainThread:469 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-05 10:55:17,059 WARNING MsgRouterThr:469 [router.py:message_loop():77] message_loop has been closed
Traceback (most recent call last):
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/interface/router_sock.py", line 28, in _read_message
    resp = self._sock_client.read_server_response(timeout=1)
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 285, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 270, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/interface/router.py", line 70, in message_loop
    msg = self._read_message()
  File "/opt/conda/envs/duckietownrl/lib/python3.8/site-packages/wandb/sdk/interface/router_sock.py", line 30, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-03-05 10:55:17,060 INFO    MsgRouterThr:469 [mailbox.py:close():115] Closing mailbox, abandoning 1 handles.
